<?php 
//$blog[] = array('id','title','blog','category','img');

	$blog[1] = array('1','Condominium in San Juan is Ready for Viewing','A few months before the completion of Aurora Residences, it has setup model units that are ready for viewing. Aurora Residences’ Model Unit has been completed and available for viewing, as early as the last week of September. Here is some information to give you an idea of what Aurora in','press','img1');
	$blog[2] = array('2','No Meat Zone in San Juan','Admit it, when you hear the word “vegetarian” the first thing that comes to mind is vegetables, lots and lots of vegetables. More often that not, just the thought of eating vegetables can never come as close to the same feeling as indulging on a plate of perfectly juicy steak, or a beautifully grilled salmon','lifestyle','img2');
	$blog[3] = array('3','The City of New Horizons','Quezon City, also known as the “City of New horizons” because of its rich culture and lifestyle. Located northeast of Manila. The city was named after Manuel Luis Quezon, the first president of the Commonwealth of the Philippines. It has one of the lowest poverty levels in the Philippines. It is also known as the','lifestyle','img3');
	$blog[4] = array('4','1 Bedroom Condominium in San Juan for Sale','Aurora Residences offers a sleek 1 bedroom unit that is now ready for viewing. Construction will be completed this December 2014. Visit us or schedule an appointment. Aurora Residences is an affordable midrise condiminium located in San Juan City right in the middle of Manila, and Quezon City that is very near malls, schools, and','blog','img4');
	$blog[5] = array('5','Luxury Amenities People Should Ignore','Are you looking to buy a big-city home? People selling properties use the word “luxury” just about as common as many pizzerias claim to be “famous”. If you ask me, luxury means to be extraordinary-something with advantage that you won’t easily depreciate. You need to look for qualities that time can’t change: location, architectural uniqueness,','lifestyle','img5');
	$blog[6] = array('6','8 Hidden Restaurants in Quezon City','Quezon City is one of the most amazing cities in Metro Manila. After all, it is home to the country’s two biggest TV networks, important cultural destinations, the top two universities in the country, and the best restaurants. There is definitely no place like Quezon City and no adventure like living here. Hiding out in','lifestyle','img6');
	$blog[7] = array('7','Studio Unit Ready for Viewing','Our model unit is ready! Check out photos for our Studio unit here at Aurora Residences. You can schedule your visit with us, or simply drop by our showroom at 150 R. Lagmay St. San Juan City Metro Manila.','blog','img7');
	$blog[8] = array('8','A New Midrise Condominium in San Juan','Aurora Residences is a luxury condominium community located in San Juan, Manila. Aurora condos range from approximately 19.9 sm to 62.73 sm, with 1-2 bedrooms, a garden, bathrooms fully equipped with an exposed tubular shower fixture, saving you time and money, Granite kitchen countertops and highly gloss painted solid wood cabinets so they are more','press','img8');
	$blog[9] = array('9','Evolution of Condominium Amenities','Ever since the rapid increase of condo projects, amenities have immensely evolved as well, to adapt to the changing needs of society. Amenities that were once considered a luxury, are now just basics. Stainless steel appliances, the fitness centre, pool, spa, hardwood and laminate floors, the concierge desk, are now standards in today’s condominium complexes.','lifestyle','img9');
	$blog[10] = array('10','Healthy Living in San Juan','Do you, or are you looking to live a fit and healthy lifestyle? Here at Greenhills, there are a number of places to do just that. From the food, to activities like yoga, boxing, and a lot more. A great and healthy restaurant located in San Juan, would be Roots Market Bistro at New Promenade','lifestyle','img10');
	$blog[11] = array('11','Why Live in a Low-rise Condominium','So what’s the difference between a high-rise and a mid-rise condominium? And how does it affect you? Midrise condominiums are usually four to six stories high. Therefore, you will not have to experience the fear of heights, and the hassle of taking the slow elevator every time you’d like to leave your home or incase','cl','img11');
	$blog[12] = array('12','Condo Living Pros','First of all we hope that everyone is safe in their homes and that their homes are safe from floods. We have seen the news and it’s not looking good. We simply want to reach out our prayers and good intentions to everyone out there. With the current situation happening, with Bagyong Mario so to','blog','img12');
	$blog[13] = array('13','Condominium Budget Basics','Living in a condominium not only means renting or buying a unit. The cost of living under a complex that is shared by a number of other residents must fall under your budget. So, you’ve decided to buy a condo in the Philippines. You want one that is within a five-minute walk to your school,','cl','img13');
	$blog[14] = array('14','The Magnolia Flavor House – The Filipino Ice Cream Legacy','So, what makes The Magnolia Flavor House so special? Because Magnolia is bringing back it’s benchmark ice cream parlor that made it’s legacy into every Filipino ice cream lover, but this time with a little twist to it. May I present to you, the Magnolia Flavor House, from your favorite frozen treats to serving home','lifestyle','img14');
	$blog[15] = array('15','When in Quezon City','What exactly is there to do in Quezon city? Well, just about everything Manila has to offer. One thing these two places don’t have in common though, would be the cost of living. It is much cheaper to live in Quezon than in Manila. If you are more of an outdoorsy type rather than being','lifestyle','img15');
	$blog[16] = array('16','Satisfying your Food Craving in San Juan','Greenhills is a venerable food mecca, with over a hundred restaurants in a multitude of cuisines from your expected Filipino, Chinese, Japanese, American and Italian cuisines, to the unexpected Indian, Tex-Mex, Taiwanese, Persian, etc. Are you the type of person who likes to follow the crowd when it comes to searching for new places to','lifestyle','img16');
	$blog[17] = array('17','Greenhills – a Shopper’s Paradise','What is Greenhills known for? It is the best place to find beautiful, branded and great quality products for a cheap price.  This is not a single mall, but rather multiple small malls packed together. There are over 2,000 stores, and has an “indoor-outdoor” theme to it. This is the best place for bargain shopping','blog','img17');
	$blog[18] = array('18','Owning a Condo vs Renting an Apartment','Condos and apartments have a lot it common. Knowing the advantages and disadvantages of each, will help you decide which makes sense for your long-term needs. For most people, it is always a bigger advantage to own rather than to rent property. Equity, one of the biggest advantages of a condominium is building equity each','lifestyle','img18');
	$blog[19] = array('19','San Juan City: A Hidden Sanctuary','People think of Metro Manila as the heart of progression where you make a name for yourself and people tend to flock to it hoping for a better future for themselves and their families. But Metro Manila in itself is huge and it’s different places offer different opportunities for everyone. We want take your focus','lifestyle','img19');
	$blog[20] = array('20','Tips on Shopping for a Condominium','One of the biggest perks about living in a condo would have to be all the desirable amenities of the building. But before you decide to purchase your dream home, you have to do some homework. Here are some tips you should read before buying a condo. Give some thought as to what you want','lifestyle','img20');


	$blogItem[1] = array('1','Condominium in San Juan is Ready for Viewing','A few months before the completion of Aurora Residences, it has setup model units that are ready for viewing. <br /><br />
Aurora Residences’ Model Unit has been completed and available for viewing, as early as the last week of September. Here is some information to give you an idea of what Aurora in store for you.<br /><br />
A luxury condominium community located in San Juan, Manila. Aurora condos range from approximately 19.9 sm to 62.73 sm, with 1-2 bedrooms, a garden, bathrooms fully equipped with an exposed tubular shower fixture, saving you time and money, Granite kitchen countertops and highly gloss painted solid wood cabinets so they are more water resistant, all rooms come fully furnished with porcelain tiles, and in the event of a power outage, there is a generator to provide light per room, refrigerator per room, and doorbell per room.<br /><br />
Aurora Residences is a modern condominium concept, offering luxurious living. A wide range of additional amenities and services is provided for the residents to enhance the living experience and help create a more serene, calm, and relaxing environment.<br /><br />
Aurora provides a concierge, which will be located at the ground to guarantee security, privacy, and exclusivity with its 24/7 exit-entry systems, as well as CCTV in all common areas.<br /><br />
The lounge is a perfect setting for you to enjoy some time with family and friends, or plan out the day while in an inviting and beautifully decorated environment, both casual and high-class.<br /><br />
These days, people are trying to live a fit and healthy lifestyle, so a gym is always a must! Aurora Residences provides state of the art fitness center, housing the latest in cardio and strength equipment.<br /><br />
Whether you’re looking to get that nice golden summer tan or relax in the resort-like 18-meter infinity pool, complete with outdoor relaxation areas located at the roof deck of Aurora.<br /><br />
One of the disadvantages of living in a condominium would be limited outdoor activity. Here at Aurora Residences, the sky lounge is a perfect place for a nice Sunday barbecue with family and friends. The stunning interiors blend well with the peaceful outdoor environment.<br /><br />
Reference: <a href="http://www.1888pressrelease.com/aurora-residences-is-ready-for-viewing-pr-546975.html">http://www.1888pressrelease.com/aurora-residences-is-ready-for-viewing-pr-546975.html</a>','press','img1');


	$blogItem[2] = array('2','No Meat Zone in San Juan','Admit it, when you hear the word “vegetarian” the first thing that comes to mind is vegetables, lots and lots of vegetables. More often that not, just the thought of eating vegetables can never come as close to the same feeling as indulging on a plate of perfectly juicy steak, or a beautifully grilled salmon fillet. Let’s face it, being a vegetarian is a big sacrifice, and it’s difficult especially when there are not a lot of restaurants that ever actually prioritize their kind.<br /><br />
Here in San Juan, there are several restaurants that only serve vegan food. So if you’re in the area, and you’re looking to eat some delicious greens, be sure to visit these places:<br /><br />
Country Vegefoods is a healthy restaurant that offers vegetarian food. Their best sellers are the tofu sisig, red rice, soya milk, and chilled taho. You can have a complete meal for only under Php100, affordable and guilt free! They also sell frozen vegetarian meats like tapa and tocino.<br /><br />
Rawvolution is another vegetarian restaurant. Their specialties are Portobello mushroom steak with rosemary garlic mashed potatoes, fettuccini Alfredo, and Mock Salmon Pate. They also have the “Raw Food Juice Remedies” which serve as remedies for your ailments.<br /><br />
Agico: Japanese vegetarian café in San Juan. It’s quite rare to find a Japanese vegetarian restaurant, Agico will definitely make you wonder why there aren’t a lot of them around. They serve your typical Gyoza Dumplings filled with mushroom, served nice and crisp on the outside and still nice and juicy on the inside. They also serve “vegan sushi” like Crispy California maki, despite that it’s missing the kani, it’s still quite refreshing. The Philadelphia torch maki is perfect for all cheese lovers out there, and a great show as well. There’s also vegan meat dishes like beef yakiniku, katsudon, and chicken teriyakidon. It’s amazing how real they make the “meat” look.<br /><br />
For more information about these restuarants, or if you’d like to find more vegan restaurants in san juan, please visit <a href="http://www.tripadvisor.com.ph">http://www.tripadvisor.com.ph</a>','lifestyle','img2');
	

	$blogItem[3] = array('3','The City of New Horizons','Quezon City, also known as the “City of New horizons” because of its rich culture and lifestyle. Located northeast of Manila. The city was named after Manuel Luis Quezon, the first president of the Commonwealth of the Philippines.<br />
It has one of the lowest poverty levels in the Philippines. It is also known as the country’s premier city due to its performance and progress.<br /><br />
The weather conditions in Quezon City are almost the same as Manile, but due to its higher elevation, the temperature is generally lower,  humidity and wind velocity are proportionately higher.<br /><br />
The city is filled with many historical landmarks, such as the San Pedro Bautista Church located in San Juan del Monte, which is the second oldest church in the country. The monumento to Gen. Lawton, the pot where the U.S. general was killed by the Katipuneros in battle after the Pact of Biak-na-Batofailed in its objective to stop the hostilities even continued after the Treaty of Paris which ended the Spanish-American war and wherein the Philippines revolutionary forces continued the war of independence against America.<br /><br />
Former President, Manuel Luis Quezon, envisioned Quezon City to be a place where the common man will find his place with dignity. In 1938, President Quezon purchased 1,529 hectares from the Diliman Estate of the Tuason Family. A year after, the National Assembly enacted the Commonwealth Act, also known as Charter of Quezon City. On October 12, 1939, Pres. Quezon signed the Bill into law, thus the city was born.<br /><br />
Quezon City has close to 60,000 business establishments. They engage mostly in the distribution of finished products and provision of basic personal services. Quezon City has great potential to support an increase in the number of big businesses in the city.<br /><br />
It is the center of the entertainment industry. Almost every local channel, variety shows, and news programs, from GMA Network, NBN, ABS-CBN, and other TV and Radio stations are based in Quezon City.<br /><br />
Out of the six cities in the Metro Manila Area, Quezon City is the largest. The strategic location provides stable ground foundation, deep water table, adequate surface drainage, and ample ground water supply. Quezon City is the second biggest in the country, being next in size to Davao City and is five time bigger than Manila, In terms of land area.','lifestyle','img3');
	

	$blogItem[4] = array('4','1 Bedroom Condominium in San Juan for Sale','Aurora Residences offers a sleek 1 bedroom unit that is now ready for viewing. Construction will be completed this December 2014.<br /><br />
Visit us or schedule an appointment.<br /><br />
Aurora Residences is an affordable midrise condiminium located in San Juan City right in the middle of Manila, and Quezon City that is very near malls, schools, and hospitals.','blog','img4');
	

	$blogItem[5] = array('5','Luxury Amenities People Should Ignore','Are you looking to buy a big-city home? People selling properties use the word “luxury” just about as common as many pizzerias claim to be “famous”.<br /><br />
If you ask me, luxury means to be extraordinary-something with advantage that you won’t easily depreciate.<br /><br />
You need to look for qualities that time can’t change: location, architectural uniqueness, views and light, ceiling heights, and sheer square footage. And ignore the stuff that is irrelevant, the stuff that doesn’t matter.<br />
To be clear: even wealthy buyers who have several homes, look at their condos as more than just a shelter, they consider it to be an investment.<br /><br />
Do fancy amenities guarantee a life of luxury? Well, both yes and no. One good example would be a building called One Ocean in Miami Beach which cost as much as $1,500 per square foot. The amenities include an “exclusive membership to a private beach club”, a “Zen Park”, and a “24-hr concierge service that you can contact directly from an iPad to create bespoke dining, event, and travel experiences.<br /><br />
<a href="http://auroraresidences.com/">Check out Aurora’s 1 Bedroom Unit if you’re looking for a condominium in San Juan for Sale.</a><br /><br />
Though I wouldn’t dwell so much on amenities. One man’s “Zen Park”, and “bespoke meal” could mean another man’s patch of grass and dinner reservations. Yet One Ocean’s Beach Club, while irresistibly charming, it is nowhere near the building. You’re probably better off buying a place at Continuum, which rests on a beachfront land across the street. Wealthy buyers have been purchasing units there for the same per-square foot prices they would have paid at One Ocean.<br /><br />
So, if you’re looking to buy a luxurious condominium, wouldn’t you rather be the clever one who enjoys the older, more drinkable wine for less? Here are some things you should never overpay for:<br /><br />
Superfluous amenities, such as champagne chambers, pet spas, mini-golf greens, massage rooms, complimentary lobby breakfast, and so on. Not one of these amenities has a lasting value.<br /><br />
The doorman, aren’t they supposed to keep you safe? Technically, it’s not their responsibility when it comes to security matters.<br /><br />
Space-age materials, avoid new modern materials you’ve never heard of. Operative words are “artificial” and “engineered” and focus on timeless, high-quality natural wood, stone and metals.','lifestyle','img5');
	

	$blogItem[6] = array('6','8 Hidden Restaurants in Quezon City','Quezon City is one of the most amazing cities in Metro Manila. After all, it is home to the country’s two biggest TV networks, important cultural destinations, the top two universities in the country, and the best restaurants.<br /><br />
There is definitely no place like Quezon City and no adventure like living here. Hiding out in one of the city’s most interesting restaurants is an adventure in itself. Here is a list of 8—consider it to be your “secret summer date guide”.<br /><br />
<span style="color: #FE6600;">Gayuma ni Maria</span> is a homey little restaurant tucked away in the quiet corner of V. Luna. The place has a whimsical Bohemian feel to it. Even the dishes themselves have names like “two become one”, “Holding Hands While Walking Pa-Swing Swing Pa”, and “Beats Sex Any Day”.<br /><br />
How about some pizza, a beer, and some peace and quiet? Sounds like heaven to me.<br /><br />
Head on over to <span style="color: #FE6600;">Leona Art Restaurant</span>. Like Gayuma, Leona is a comfy old house converted into a restaurant.<br /><br />
<span style="color: #FE6600;">Van Gogh is Bipolar</span> is a restaurant hidden in the courtyard of an apartment along Maginhawa street. Only a dozen customers can experience their food each night. Like Van Gogh, the owner of the restaurant was also diagnosed with bipolar disorder. The concept of this restaurant is eating for happiness, thus the happy hormones-inducing menu.<br /><br />
<span style="color: #FE6600;">Thai pan</span> is a modern Thai bistro. They serve all the Thai comfort food you know and love, like shrimp cakes, pad Thai, tom yum. A great choice if you’d like to just hide out during the day.<br /><br />
<span style="color: #FE6600;">Lola Café + Bar</span> is probably the closest you’ll ever get to home. The restaurant is a converted ancestral house. They serve home made cocktails and home-cooked food. It’s like going back to your childhood days, visiting your lola for lunch.<br /><br />
Looking to spend a fancy night out? <span style="color: #FE6600;">Lemuria Gourmet</span> offers French-Mediterranean cuisine, high-dining style. A perfect place for impressing your date.<br /><br />
Another house converted to a restaurant would be <span style="color: #FE6600;">Napa</span>. The restaurant offers a wide selection of comfort food- brick-oven pizza, soups, pork skewers, pasta, fine wines, even cake!<br /><br />
Last but not the least is <span style="color: #FE6600;">Uno</span> located in Tomas Morato Quezon City. The best part about Uno is that what you see is what you get. The building and the interiors say it all—their food is just as delicious and comforting as they are elegant. You see the chic nondescript concrete, wood and wrought iron building and you expect to sit down, enjoy your meal  and conversation.','lifestyle','img6');
	

	$blogItem[7] = array('7','Studio Unit Ready for Viewing','Our model unit is ready!<br /><br />
Check out photos for our Studio unit here at Aurora Residences.
You can schedule your visit with us, or simply drop by our showroom at 150 R. Lagmay St. San Juan City Metro Manila.','blog','img7');
	

	$blogItem[8] = array('8','A New Midrise Condominium in San Juan','Aurora Residences is a luxury condominium community located in San Juan, Manila. Aurora condos range from approximately 19.9 sm to 62.73 sm, with 1-2 bedrooms, a garden, bathrooms fully equipped with an exposed tubular shower fixture, saving you time and money, Granite kitchen countertops and highly gloss painted solid wood cabinets so they are more water resistant, all rooms come fully furnished with porcelain tiles, and in the event of a power outage, there is a generator to provide light per room, refrigerator per room, and doorbell per room.<br /><br />
Aurora Residences is a modern condominium concept, offering luxurious living. A wide range of additional amenities and services is provided for the residents to enhance the living experience and help create a more serene, calm, and relaxing environment.<br /><br />
Safety is always everyone’s number one priority when shopping for a condo. Aurora Residences provides a concierge, which will be located at the ground to guarantee security, privacy, and exclusivity with its 24/7 exit-entry systems, as well as CCTV in all common areas.<br /><br />
The lounge is a perfect setting for you to enjoy some time with family and friends, or plan out the day while in an inviting and beautifully decorated environment, both casual and high-class.<br /><br />
One of the downsides of living in a high rise condominium, especially when you’re living on one of the top floors, would be “elevator traffic”. Aurora is fitted with 2 high-speed elevators, making your morning rush to school or work so much easier.<br /><br />
These days, people are trying to live a fit and healthy lifestyle, so a gym is always a must! Aurora Residences provides state of the art fitness center, housing the latest in cardio and strength equipment.<br /><br />
Whether you’re looking to get that nice golden summer tan or relax in the resort-like 18-meter infinity pool, complete with outdoor relaxation areas located at the roof deck of Aurora.<br /><br />
One of the disadvantages of living in a condominium would be limited outdoor activity. Here at Aurora Residences, the sky lounge is a perfect place for a nice Sunday barbecue with family and friends. The stunning interiors blend well with the peaceful outdoor environment.<br /><br />
<a href="http://www.1888pressrelease.com/aurora-residences-a-new-mid-rise-luxury-condo-building-in-s-pr-544134.html">http://www.1888pressrelease.com/aurora-residences-a-new-mid-rise-luxury-condo-building-in-s-pr-544134.html</a>','press','img8');


	$blogItem[9] = array('9','Evolution of Condominium Amenities','Ever since the rapid increase of condo projects, amenities have immensely evolved as well, to adapt to the changing needs of society. Amenities that were once considered a luxury, are now just basics.<br /><br />
Stainless steel appliances, the fitness centre, pool, spa, hardwood and laminate floors, the concierge desk, are now standards in today’s condominium complexes. Business centres, which were all the rage a couple years ago, have been replaced with conference rooms or board rooms, large pools are being replaced with smaller ones, or spa-like areas with hot tubs and saunas.<br /><br />
New condominium amenities include the yoga studio and massage room, theaters with the big screen and comfortable chairs, fancy party rooms, guest suites to allow owners to make use of common amenities and at the same time, save on the square footage in their unit.<br /><br />
More luxurious amenities feature private wine cellars, infinity pools, humidors, and screening rooms.<br /><br />
Up and coming trends to look for would be Wi-Fi connectivity, media rooms, rooftop sculpture gardens, art collections, grocery stores, tennis courts, and even pet walks.<br /><br />
Today, it’s all about looking and feeling your best. One of most important feature buyers seem to be interested in are the gym facilities.<br /><br />
Another amenity buyers consider to be very important would be the 24-hour security. It makes residents feel more secure and comfortable in their home. And for most parents, peace of mind when leaving their kids at home.<br /><br />
Visitor parking, another amenity buyers prefer to have. Because we live in an urban area, parking can be quite difficult to find, and costly when available. Condo owners like to see more spots for visitors and guests.<br /><br />
Though amenities are attractive to many buyers, smart buyers are aware of the fact that the more amenities a building has, the higher the condo fee will be.<br /><br />
So as new condos continue to emerge with bigger and better state-of-the-art amenities, remember the features that always help with resale or add any value to a property are a modern and updated lobby security, especially when it comes to single females who play a large role in today’s real estate market. Rooftop patios with a great view are also coveted during the warmer months.<br /><br />
Aurora Residences is a <a href="http://auroraresidences.com/">midrise luxury condonimium in San Juan</a>. It’s amenities are implemented with utmost quality with a roof deck pool, fast elevators, a sky lounge and a very accommodating reception area.','lifestyle','img9');
	

	$blogItem[10] = array('10','Healthy Living in San Juan','Do you, or are you looking to live a fit and healthy lifestyle? Here at Greenhills, there are a number of places to do just that. From the food, to activities like yoga, boxing, and a lot more.<br /><br />
A great and healthy restaurant located in San Juan, would be Roots Market Bistro at New Promenade. The place looks pretty much like an indoor garden. The owner or Roots Market Bistro also mans Wafu, stackers and others. Roots only uses quality ingredients in their cookery, such as Arugula from France, and breads baked in-house, even their bacon is made in-house. Their food is not only simple yet elegant, but is extraordinary in taste as well. Their specialties are the BLT, Spinach Mushroom omelette, and the vegetable Aglio Olio.<br /><br />
Bodhi Vegetarian Restaurant is located in Greenhills, San Juan. They serve veggie meat made from soy! But has the same form and texture as real meat. They serve food like chopsuey, adobo, curry, kare-kare (which btw uses mushrooms for their fish paste or bagoong and taste exactly like the real thing!), and lots more.<br /><br />
Bliss Yoga, is a yoga studio located in Greenhills, San Juan. The place has a very calming atmosphere, with Asian themed furniture and décor. For those of you coming from work, lockers provided along with a changing area for you to strip down into your yoga wear. For all you yoga newbies, matt loans are available and energy and hydrating drinks are available upon entering. There are also guidelines for all you beginners who are very much interested in this excersize. For more info, visit their website: <a href="http://www.blissyogamanila.com/">http://www.blissyogamanila.com</a><br /><br />
Fitness First is one of the most popular fitness chains in the Philippines. Although there are now several fitness first gyms around the metro, fitness first branch in greenhills was the pioneer when it first came to the Philippines. It is a divided into two storeys and though this branch is one of the oldest, they are still able to maintain its cleanliness and upgrade their equipment.<br /><br />
Fight Factory Manila is a new and upcoming fitness franchise that has been growing within metro manila that promotes Brazilian Jiujitsu, Muay Thai, Boxing, HIIT. Fight Factory Manila has a newly opened gym in Greenhills but it roots from Quezon City in Tomas Morato to be specific. To learn BJJ, Boxing, and Muay Thai, there is no better place to do it than Fight Factory Manila.<br /><br />
For people who prefer to exercise outdoors, there are over forty bicycling routes, and at least four running routes within the area of San Juan.<br /><br />
If you live within the vicinity of San Juan which is in the middle of Quezon City, Manila, and Ortigas, you will have no excuse not to get fit with all the options we have presented to you. Stay fit, and stay healthy.<br /><br />
<a href="http://auroraresidences.com/">Aurora Residences</a> is a midrise condominium located in San Juan City. A place very accessible to Greenhills, Manila, and Quezon City that is near top schools and the best hospitals. Aurora will be completed this December 2014, get your units today.','lifestyle','img10');
	

	$blogItem[11] = array('11','Why Live in a Low-rise Condominium','So what’s the difference between a high-rise and a mid-rise condominium? And how does it affect you?<br /><br />
Midrise condominiums are usually four to six stories high. Therefore, you will not have to experience the fear of heights, and the hassle of taking the slow elevator every time you’d like to leave your home or incase of emergency. Owning a pet would me more convenient as well.<br /><br />
For those of you who like your privacy, midrise condominiums have fewer residents, which means less noise and fewer parties. It also makes it easier to maintain a clean environment. They are usually located in quiet residential areas, thus offering more privacy.<br /><br />
Because high-rise condominiums have space for more people, they are much busier and require more interaction. With that many people living in a building, you’re bound to have a noise nuisance from neighbors directly above, below, or next to you. Residents usually complain about dogs barking or loud music in high-rise condominiums.<br /><br />
High-rise condominiums also cost more due to the more luxurious and unnecessary amenities, superior location, and maintenance of the entire building as well.<br /><br />
Another disadvantage to living in a high-rise condominium would be move-in day, moving heavy furniture and appliances upstairs can be challenging. The space of corridors and hallways can be small. If you’re planning on hiring movers, you can expect to pay more than if you lived in a more accessible condominium.<br /><br />
Living in a midrise condominium, it is also much safer when it comes to certain emergencies like fire or earthquakes.<br /><br />
It is easier to evacuate a midrise condominium during a fire. High-rise condominiums’ residents are usually ordered by the fire chief to remain inside their condos while the fire is being extinguished. Unlike high-rise condominiums can reach up to 20 storeys or more, midrise condominiums only reach up to 6 storeys, and fire truck ladders can only reach up to 100 feet, which is 7 storeys.<br /><br />
During the occurrence of an earthquake, the taller the building, the more it sways during an earthquake. Midrise condominiums have more stability, which means minimal movement.<br /><br />
So if you’re looking to buy a condo, consider a midrise condominium building. Be sure to weigh in these disadvantages of owning a high-rise condo before you decide to sign a lease.<br /><br />
Aurora Residences is an <a href="http://auroraresidences.com/">affordable yet luxury midrise condominium</a> located in San Juan City Philippines.','cl','img11');
	

	$blogItem[12] = array('12','Condo Living Pros','First of all we hope that everyone is safe in their homes and that their homes are safe from floods. We have seen the news and it’s not looking good. We simply want to reach out our prayers and good intentions to everyone out there. <br/><br/>
With the current situation happening, with Bagyong Mario so to speak, we can’t just be thankful enough of our current situation living in a condominium here in Metro Manila. Here are some of the things that are very common but in times like these very thankful to have. <br/><br/>
<h4> No Brownouts</h4><br/><br/>
Most condominiums are situated in well setup places and that the energy infrastructure is very much intact. At the worst scenarios i.e. the last mega storm hit, there was still electricity from the establishment’s generator sets. <br/><br/>
Elevators are still functional and yes life as it is goes on normally. <br/><br/>
<h4> Midrise Parking Spaces </h4> <br/> <br/>
Some condominiums have parking areas set up to the 10th floor and if your vehicle is parked in those spaces you would not worry at all with the increasing flood happening all over. <br> </br>
<h4> Convenience with Food and other Basic Resources </h4><br/> <br/>
Most condominiums have establishments setup in the ground floor or probably have a Mini-Stop or 711 just around the corner. Pretty convenient where you can’t travel much, all you need is a good umbrella, jacket and some steps to go and you’re set.
<br/> <br/><h4> Clean Flowing Water </h4>
<br/> <br/>Well not all but most condominiums have a structure of water coming into each unit. This is something we appreciate in units that we live in as there are places which we have lived before where when there is no electricity automatically there is no water.<br> <br/>
I guess these are simple things that we tend to appreciate in times like these. And for everyone that are affected in the storm, we hope that you and your families are safe.<br> </br>
Aurora Residences is a Midrise <a href=”#”> affordable Condominium in San Juan</a>. It is located near hospitals, schools, and is easily accessible. It is in the heart of the metro being in the middle of 3 cities Quezon City, Manila, and it’s very own San Juan City. Inquire about our units today.','blog','img12');
	

	$blogItem[13] = array('13','Condominium Budget Basics','Living in a condominium not only means renting or buying a unit. The cost of living under a complex that is shared by a number of other residents must fall under your budget. <br/><br/>
So, you’ve decided to buy a condo in the Philippines. You want one that is within a five-minute walk to your school, the mall, and markets. But your first instinct would be to make sure it offers full security and recreational facilities at the ground floor. Who doesn’t dream of living a life of comfort and convenience? <br/><br/>
Here are some things you may need to know before you purchase a condo, so that you don’t fall for any common condo buyer mistakes: <br/><br/>
First on your list, would be your <i>monthly amortization</i>. Like any smart buyer, choose the payment strategy that matches your monthly income. Typically, you need to make a down payment aside from your monthly installments. <br/><br/>
After the full payment, next would be to register the condominium’s title to your name.  As the new owner of this real property, The Register of Deeds will issue you an Owner’s Duplicate Condominium Certificate of Title. The cost of tax should not exceed 4% of your purchased price. <br/><br/> After you’ve invested in real estate in the Philippines, you are liable to pay real property tax according to Philippine Laws. <br/><br/>
For condo tenants, the most basic expense would be the rent. Most of the time, landlords require advanced rental and security deposit. Though there are standard prices to which expenses are charged to the tenant and the unit owner, it would be best to state them in the contract of lease. <br/><br/>
As a condo resident, you are automatically a member of the Homeowners Association that is run by a Board of Directors. Which means you are also partly liable for the cost of maintaining the common areas with common residents through monthly association dues. This includes things like grass mowing, pool cleaning,, and interior work such as painting, carpet cleaning, elevator maintenance, etc. <br/><br/>
Condo units usually have their own water and electric meters, so residents pay directly to the service provider based on their consumption. Same thing goes for a telephone line. <br/><br/>
Aside from the convenience and accessibility, the advantage of owning a condo is being free from all the worries of maintenance and security. All it requires is to fit the charges and fees into your condo budget and be sure to get the value of what you pay for. <br/><br/>
<a href=”#”> Aurora Residences Condominiums </a> is a great value for money property combining the luxury of a midrise condomonium at a very affordable price.','cl','img13');
	

	$blogItem[14] = array('14','The Magnolia Flavor House – The Filipino Ice Cream Legacy','So, what makes The Magnolia Flavor House so special? <br/><br/>
Because Magnolia is bringing back it’s benchmark ice cream parlor that made it’s legacy into every Filipino ice cream lover, but this time with a little twist to it. May I present to you, the Magnolia Flavor House, from your favorite frozen treats to serving home comfort food dishes. Magnolia will definitely give your taste buds a wonderful experience. <br/><br/>
For the young kids of the 80’s and 90’s, Magnolia was a place of many fond memories and experiences as families spent their weekends there for delicious desserts. And just as much, Magnolia was a place for teenagers, couples, and even seniors to hang out there as well. <br/><br/>
Magnolia Flavor House is located at the garden of the Robinson’s Magnolia Mall in Quezon City. <br/><br/>
Now that the Magnolia Ice Cream Parlor has risen from the ashes, many people who’ve been to the former ice cream parlor will surely return to reminisce as well as to make new memories over a banana split, parfait, or maybe a peach melba. <br/><br/>
As soon as you sit down at your table, you are immediately given menus. Though the place specializes in desserts, they’ve also made a few additions to their menu such as sandwiches, pizza, burgers, fries, and other food people might be interested in. <br/><br/>
One of their most famous desserts, the banana split, just seems like any other banana split you’d find at an ice cream parlor. If you look closely however, you’ll find that they’re chocolate coated! Magnolia’s signature to their banana split, perhaps. <br/><br/>
The whole feels very inviting, with glass windows surrounding the entire shop, and with paint furnishings in blue, yellow, and white. The place has a very modern feel to it. <br/><br/>
You will definitely be coming back for more, wanting to try out all their other desserts. Despite all the new , particularly foreign ice cream parlors, there’s just something about the classics like Magnolia that brings back all those wonderful memories. <br/><br/>
Aurora Residences is just a few blocks away from Robinsons Magnolia, convenient and <a href=”#”> affordable condominiums near Quezon City</a>. ','lifestyle','img14');
	

	$blogItem[15] = array('15','When in Quezon City','What exactly is there to do in Quezon city? Well, just about everything Manila has to offer. One thing these two places don’t have in common though, would be the cost of living. It is much cheaper to live in Quezon than in Manila. <br/> <br/>
If you are more of an outdoorsy type rather than being a homebody, then Quezon city is the place for you. There are over 70 fun and exciting things you can do at Quezon. <br/> <br/>Worried about how you’re going to get there? Transportation is never a problem. You’re free to choose between buses, trains, or jeeps, depending on where you are or where you’d like to go. Most major thoroughfares are now located at Quezon city, including the Metro Rail and the Light Rail Transit. <br/> <br/>
If you love to “shop till you drop”, there are over forty shopping areas here in Quezon city. One of which happens to be the largest mall in the entire Philippines. <br/> <br/>
They have 3 large shopping malls, (SM Fairview, TriNoma, SM North) one of which happens to be the largest mall in the Philippines. There’s also a park with a small zoo at the Quezon Memorial wherein they throw extremely large Christmas fiestas. <br/> <br/>
The Araneta Coliseum is attached to a mall, they throw large events like concerts, fights, games, etc. Complete with the first and only Taco Bell in the entire Philippines. Who doesn’t love Tex-Mex. This is definitely a landmark worth noting. <br/> <br/>
If you enjoy a good scenery, jogging or walking during the day, or you’d like to spend the day to bond with family and friends, Quezon City Circle is a good place to do just that. People go there to jog or walk as early as six in the morning.There’s an aerobic dance area as well. <br/> <br/>
Would you like to see yourself on television? Or if you’re here on vacation, would you like your family and friends from back home to know you’re vacationing with Philippine celebrities? Quezon houses most television and radio networks, such as ABS-CBN, Net 25, NBN, RPN, IBC, TV5, GMA, GEM TV, and UNTV. <br/> <br/>
If you are the religious type, Quezon city offers a number of churches. Be sure to visit the following places: Iglesia ni Kristo, Sto. Domingo Church, Christ the King church, and Saint Peter Church. <br/> <br/>
Another great thing about Quezon city is the education. There are over 30 schools. They have the most number of secondary schools, elementary schools, and several educational institutions. Two of the most well-known would have to be University of the Philippines, and Ateneo de Manila University. Several Philippine presidents attended courses in University of the Philippines (UP). <br/> <br/>
Quezon is also the home of several historic events The EDSA People Power, Battle of La Loma, and Cry of Pugad Lawin. <br/> <br/>
Here’s a little trivia about Quezon city which you probably don’t know. What prehistoric animal lived in this area eons ago? The answer is, it was a type of mammoth or elephant. Something to impress your kids the next time you plan to visit Quezon. That is also why some people believe it to be the reason why legislation moves so slow at the Batasan.
Aurora Residences is an affordable condominium located in the San Juan City which very near Manila and Quezon City. <span style="color: #FE6600;"> Buy Condos in San Juan</span> today!','lifestyle','img15');
	

	$blogItem[16] = array('16','Satisfying your Food Craving in San Juan','Greenhills is a venerable food mecca, with over a hundred restaurants in a multitude of cuisines from your expected Filipino, Chinese, Japanese, American and Italian cuisines, to the unexpected Indian, Tex-Mex, Taiwanese, Persian, etc. <br/><br/>
Are you the type of person who likes to follow the crowd when it comes to searching for new places to eat? Here are three relatively new restaurants you might want to visit. <br/><br/>
Huat Pot is an all you can eat healthy Taiwanese shabu-shabu buffet. They have every possible meat you can ever imagine. A meat-lover’s paradise.  Because this is a Taiwanese hotpot buffet, expect a lot of balls! Lobster balls, fish with coriander balls, squid balls, you name it! And finally, the most awaited and exciting part, cooking! But don’t forget to leave room for dessert! You will definitely have a great time, and want to come back the very next day. <br/><br/>
Munchtown, the great thing about this place is that it’s located near the movie theater which allows their customers to order their grub and have it delivered inside the cinema. This is definitely the place to get the ultimate movie snack. Munchtown serves the kind of food that’s fast, delicious, and visually appetizing. <br/><br/>
Torch has sushi, pizza, burgers, even steak fondue, which is a rib-eye meltique that truly does melt in your mouth! Several types of food, but Torch pulls it off. Definitely recommend this place! <br/><br/>
These are only a few of the many new places to eat at Greenhills Shopping Center. I guess it’s safe to say that you can never go wrong with Greenhills. What don’t they have? From clothes, to bags, to gadgets, to artifacts, and delicious food! There is always something new to see, to eat, and to experience for everyone, no matter how many times you’ve been there. <br/><br/>
If you’d like to find out more about other restaurants at Greenhills Shopping center, their menu, reviews, price range, exact location, etc., check out websites like <a href=”www.munchpunch.com”>, </a> <a href=”www.zomato.com” </a> , <a href=” www.clickthecity.com” </a>.','lifestyle','img16');
	

	$blogItem[17] = array('17','Greenhills – a Shopper’s Paradise','What is Greenhills known for? It is the best place to find beautiful, branded and great quality products for a cheap price.  This is not a single mall, but rather multiple small malls packed together. There are over 2,000 stores, and has an “indoor-outdoor” theme to it. <br/><br/>
This is the best place for bargain shopping. From clothes, bags, shoes, gadgets, baby items, jewelry (especially pearls), cellphones, computers, watches, all sorts of crazy gadgets, and even flowers and plants! This place has it all. It’s also a great place buy “pasalubongs” to give friends and family. <br/><br/>
You can spend hours shopping! But spend your money wisely, always look for the better offer and don’t be shy to bargain. Haggling is part of the fun! <br/><br/>
Engineers and accountants would visit Greenhills to buy the latest cellphones and electronic gadgets at very attractive prices. Not only can you buy cellphones, but you can sell your old one’s here too. It’s the cellphone capital of the country. <br/><br/>
Greenhills is the most incredible place to find pearls. Some foreigners like to call it “Pearl Paradise”, because of all the different varieties and outrageously cheap prices. Some people even travel from all over the world just to see our beautiful pearls. <br/><br/>
Greenhills is also famous for it’s wide variety of food. Here you will find common places like McDonald’s, Krispy Kreme, Dunkin’ Donuts, Jollibee. As well as much more luxurious restaurants like Brasserie Cicou, Calderón, Wafu, Choi Garden, etc. <br/><br/>
But endless shopping and delicious food is not all that Greenhills has to offer. <br/><br/>
Watch the latest movies at Greenhills Cinemas. Enjoy concerts, comedy shows, poetry reading, all the way to praise and worship at the Music Museum. If you’re looking to watch amazing performances up close and personal or throw a party, T.E.A.T.R.I.N.O. is the place to be. <br/><br/>
You can easily spend the whole day here. <br/><br/>
The area is clean, air conditioned, and toilets are easy to find. Products are interesting to buy. There’s a wide variety of food options to choose from. Parking spaces are more than enough, and the mall is easy to get to if ever you plan to commute. <br/><br/>
Greenhills provides a public transport terminal for Fairview, Marikina, Pasig, and ortigas center, as well as a Greenhills to Tiendesitas shuttle service that makes trips every hour from 2-8pm everyday. <br/><br/>
Aurora Residences is just a few minutes away from Greenhills, it’s one of the most affordable condominiums that’s located near Greenhills (San Juan), Quezon City and Manila. If you are a resident of Aurora, shopping will never be a problem.
','blog','img17');
	
	$blogItem[18] = array('18','Owning a Condo vs Renting an Apartment','Condos and apartments have a lot it common. Knowing the advantages and disadvantages of each, will help you decide which makes sense for your long-term needs. <br/><br/>
For most people, it is always a bigger advantage to own rather than to rent property. <br/><br/>
Equity, one of the biggest advantages of a condominium is building equity each month. Renters on the other hand, pay a set monthly amount to the owner for use of the space. So instead of renters building equity, they are helping the owner of the apartment building build equity. <br/><br/>
When it comes to monthly costs, there’s not much of a difference between the two. People who rent apartments pay for utilities, insurance, phone service, internet, cable, that is if you choose to have them. As for condo owners, you’re required to pay your monthly mortgage and association fees, whether you choose to use it or not. If you prefer to control your monthly expenses, living in a condo could be a disadvantage for you. If you’d like to reduce your housing costs, then owning a condo would be a definite advantage. <br/><br/>
Now for the maintenance, as a condo owner, you will not have to worry about any outside exterior maintenance or landscaping. For apartment owners, you won’t have to worry about them either unless specified in your lease. <br/><br/>
When you compare owning a condo to leasing an apartment, one of the advantage for condo owners is that they have a long-term mortgage. Which means they don’t have to worry about lease renewals. Apartment leases usually require approval for each person who lives there. A condo belongs to you and you can share it with whomever you please.
You will have to secure financing in order to buy a condo, unless you make a cash offer. You will also have to come up with closing costs, in addition to the down payment. Upfront costs are a disadvantage compared to getting an apartment, which usually requires security deposit and first month’s rent. <br/><br/>
When you rent an apartment, you really have no say with the way the space is designed. However, when you own a condo, you can change absolutely anything within the space because that property belongs to you. From painting to re-carpeting, and even replacing your cabinets is always acceptable to your condo association. (just make sure you have building permits to replace your cabinets) <br/><br/>
Owning a condo is having a potential profit-maker, an asset, and you stand to make a significant profit if you sell your condo at the right economic climate. Or there is always that option to buy a new condo and pay off the initial one by renting it out.','lifestyle','img18');
	
	$blogItem[19] = array('19','San Juan City: A Hidden Sanctuary','People think of Metro Manila as the heart of progression where you make a name for yourself and people tend to flock to it hoping for a better future for themselves and their families. <br/><br/>
But Metro Manila in itself is huge and it’s different places offer different opportunities for everyone. <br/><br/>
We want take your focus on San Juan City. You probably don’t realize it but the City of San Juan is like a hidden sanctuary. Why? Well simply because everything you need is just at the reach of your fingertips! . <br/><br/>
LET US GIVE SOME OF THE REASONS WHY YOU SHOULD CONSIDER LIVING IN SAN JUAN CITY METRO MANILA. <br/><br/>
<h1>Historical Value and Earthquake Risks Free</h1> <br><br/>
San Juan is one of the best places to live in. It is a historic city, found right in the heart of Metro Manila. It is also the smallest city in Metro Manila.
Because San Juan is located in the heart of region’s central plateau, the city is free of earthquake damage risks. <br><br/>
<h1> Shopping and Dining <h1> <br/> <br/>
San Juan is synonymous to Greenhills. Greenhills Shopping center is the best place to find beautiful, branded and great quality products for a cheap price.  There are over 2,000 stores. It is also known for it’s wide variety of pearls. Most foreigners prefer to call it, “Pearl Paradise”. People fly from all over the world, just to see it. <br/><br/>
You want to live somewhere accessible, a place where everything you probably need in your home is just a few minutes drive away. <br/><br/>
Now if you are craving for anything in particular? Not to worry!
<br/> <br/> San Juan is also famous for their wide selection of restaurants. Common places like McDonald’s, Subway, Krispy Kreme, Jollibee, etc. But if you’re looking for a place to spend a much more luxurious day or night, there’s also places like Brasserie Cicou, Calderón, Wafu, Choi Garden, etc. <br/> <br/>
<h1> Education for your Kids </h1>
When you plan for your own family and kids education is one of the most important things that come to mind. And location is one of things you consider where your child goes to school. <br/> <br/>
San Juan has over 20 schools that of good quality for you to choose from. Here are some of the most well-known: Xavier School (an all boys school), The Immaculate Conception Academy – Greenhills (Chinese school exclusively for girls), and De La Salle High School Greenhills, which is a private catholic school exclusively for boys and is run by Roman Catholic Brothers of the Christian schools- Philippine district, and there are much more to choose from. <br/> <br/>
<h1> Churches </h1>
If you are Catholic you will then appreciate San Juan even better. There are five well-known churches within the area, some of which were built during the Spanish era, showing the deep Christian heritage of the Filipino people. Church of San Juan del Monte (Santuario Del Santo Cristo), St. John the Baptist Parish (Pinaglabanan Church), and Chapel of our Lady of the Miraculous Medal (140 rue du Bac), Chapel of the Holy Family, and Mary the Queen of Parish. <br/><br/>
San Juan is known for celebrating the feast of their patron, St. John the Baptist. Every June 24, children and grown ups all participate to honor the Feast day of San Juan Bautista, with the traditional “basaan” or “buhusan”.  They love to engage in water wars and other wet games using pails, hoses, or even water pistols. This symbolizes the birth of St. John, who cleansed and prepared the people for the coming of Jesus Christ by baptizing them with water. So a warning to all those who have school or work on that day, be sure to carry extra clothes! <br/><br/>
So the question really is Why Not Live in San Juan!?','lifestyle','img19');

	$blogItem[20] = array('20','Tips on Shopping for a Condominium','One of the biggest perks about living in a condo would have to be all the desirable amenities of the building. But before you decide to purchase your dream home, you have to do some homework. Here are some tips you should read before buying a condo. <br/><br/>
Give some thought as to what you want and expect in a condo. If you’re not interested in a gym or a pool, or other amenities that some condos provide, have in mind that the monthly association fees as well as the condo’s price will reflect whether you make use of the facilities or not.<br/>
Some of these deals may be very tempting, but buyers need to think as if they’re signing a business agreement when purchasing a condo. <br/><br/>
If you have an idea on what you’re interested in, a real estate agent can be great help to find properties you may not even be able to find on your own. <br/><br/>
Take a look at the minutes of the board meetings to see what owners have been griping about. If everyone is complaining about the gardener’s absence, plumbing, or pool maintenance, you know the complex is having management difficulties.<br/><br/>
Ask if they’ve done a reserve-fund review in the past five years. Lester Giese, author of “The 99 Best Residential and Recreational Communities in America”, recommends the ff. formula:<br/><br/>
If the complex is less than ten years old, the reserve-fund should have 10% of the cost of replaceable items such as roofs, roads, and tennis courts. For complexes between 10 and 20 years old, the repairfund should be at 25% to 30%. At 20 years, that amount should be 50% or more. Residents who brag that they don’t pay much in maintenance may be in a complex that has poor upkeep or that is living beyond its means.
“Most buyers don’t think of it, but you need to ask for a copy of the association’s budget” Berger says. You are not likely to receive one from the association, but you may request for a copy as a potential buyer.<br/><br/>
Get a copy of the certificate of insurance, that is a summary of the association’s policy. See if the replacement costs that the policy covers is an accurate estimate of rebuilding costs. Ensure that the policy has a building ordinance clause, which means the insurance will cover the cost of bringing the building to code if rebuilding occurs.','lifestyle','img20');



?>	